### PR TITLE
MSSQL Migration fixes

### PR DESCRIPTION
**Pull request by tsdogs**
As dektrium seems to be taking ages to merge, could you please also merge my MSSQL improvements to migrations?

Original pull request can be found here:
https://github.com/dektrium/yii2-user/pull/843

### CODE REVIEW

**Comment by thyseus** [comment]
hey tsdogs, is dektrium available again?

**Comment by tsdogs** [comment]
Not that I know of. That's why I created this pull request.
I deleted the branch 'cause I basically messed up a little with branches :)
I might create a new pull request for this once I understand how to handle the branches with composer and github correctly.

**Comment by thyseus** [comment]
See here: https://github.com/dektrium/yii2-user/issues/903 - maybe its time to really do sort of an "official" fork ?

**Comment by tsdogs** [comment]
Yeah I saw it. I support the fork if there's no way to see where dektrium got lost.

**Pull request closed without merging**
